version: "3.9"
networks:
    web:
        driver: bridge
services:
    serverd:
        build: serverapp/
        command: ["python", "-u", "server.py"]
        environment:
            SERVER_LISTEN_URI: tcp://0.0.0.0
        ports:
            - "8000"
            - "8001"
            - "8002"
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    clientd:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        scale: 8
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME:
            TESTING:
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/

