version: "3.9"
networks:
    web:
        driver: bridge
services:
    serverd:
        build: serverapp/
        command: ["python", "-u", "server.py"]
        environment:
            SERVER_LISTEN_URI: tcp://0.0.0.0
        ports:
            - "8000"
            - "8001"
            - "8002"
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client1:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client1
            TESTING:
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client2:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client2
            TESTING:
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client3:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client3
            TESTING:
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client4:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client4
            TESTING:
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client5:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client5
            TESTING:
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/

