version: "3.9"
networks:
    web:
        driver: bridge
services:
    serverd:
        build: serverapp/
        command: ["python", "-u", "server.py"]
        environment:
            SERVER_LISTEN_URI: tcp://0.0.0.0
        ports:
            - "8000"
            - "8001"
            - "8002"
        networks:
            web:
    clientd:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME:
        networks:
            web:

