version: "3.9"
networks:
    web:
        driver: bridge
services:
    serverd:
        build: serverapp/
        command: ["python", "-u", "server.py"]
        environment:
            SERVER_LISTEN_URI: tcp://0.0.0.0
        ports:
            - "8000"
            - "8001"
            - "8002"
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client1:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client1
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client2:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client2
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client3:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client3
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client4:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client4
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client5:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client5
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client6:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client6
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client7:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client7
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client8:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client8
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client9:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client9
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/
    client10:
        build: clientapp/
        command: ["python", "-u", "client.py"]
        environment:
            SERVER_CONNECT_URI: tcp://serverd
            DISPLAY: 
            NAME: client10
        networks:
            web:
        volumes:
            - type: bind
              source: ./log/
              target: /code/log/

